"""
Ranking + "why this" + Next-Best-Action. Owned by P3.

EXPOSES:  recommend(eligible, profile, cart) -> (list[Recommendation], list[str] nba)

MOCK:  score by feature/brand match; template "why"; simple nudges.
REAL:  same deterministic scoring, but the `why` text is generated by OpenAI,
       grounded ONLY in the product's real fields + the profile. Any failure
       (missing/bad key, rate limit, network, refusal) falls back to the
       template for that one product - one bad call never breaks the whole list.

GUARDRAIL (must always hold): every Recommendation.product_id MUST be in the
eligible set. The LLM can phrase the "why" but can NEVER introduce a product.
"""
import logging

from app.config import MOCK_MODE
from app.contracts.models import Cart, EligibleProduct, PreferenceProfile, Recommendation

logger = logging.getLogger(__name__)


def _score(e: EligibleProduct, profile: PreferenceProfile) -> float:
    p = e.product
    s = 0.0
    s += len(set(profile.features_mentioned).intersection(p.features)) * 2
    if p.brand in profile.brands_viewed:
        s += 2
    if p.brand in profile.rejected:
        s -= 5
    if profile.budget_monthly_max and p.price_monthly:
        # reward being comfortably under budget
        s += max(0, (profile.budget_monthly_max - p.price_monthly) / 10.0)
    return s


def _why_template(e: EligibleProduct, profile: PreferenceProfile) -> str:
    p = e.product
    bits = []
    matched = set(profile.features_mentioned).intersection(p.features)
    if "camera" in matched:
        bits.append("strong camera")
    if "eu_roaming" in matched:
        bits.append("EU roaming for travel")
    if "unlimited" in matched or "5g" in matched:
        bits.append("fast data")
    reason = ", ".join(bits) if bits else "a great all-round fit"
    budget_note = ""
    if profile.budget_monthly_max and p.price_monthly:
        budget_note = f" and it's within your €{int(profile.budget_monthly_max)}/mo budget"
    return f"{p.name} matches your need for {reason}{budget_note}."


def _why(e: EligibleProduct, profile: PreferenceProfile) -> str:
    if MOCK_MODE:
        return _why_template(e, profile)
    try:
        return _why_openai(e, profile)
    except Exception as ex:  # noqa - one bad call must not break the recommendation
        logger.warning("OpenAI 'why' generation failed for %s (%s); using template.", e.product.id, ex)
        return _why_template(e, profile)


def recommend(
    eligible: list[EligibleProduct],
    profile: PreferenceProfile,
    cart: Cart | None = None,
) -> tuple[list[Recommendation], list[str]]:
    ranked = sorted(eligible, key=lambda e: _score(e, profile), reverse=True)
    top = ranked[:3]

    recs: list[Recommendation] = []
    for i, e in enumerate(top):
        recs.append(Recommendation(
            product_id=e.product.id,
            rank=i + 1,
            score=round(_score(e, profile), 2),
            why=_why(e, profile),
            bundle=_suggest_bundle(e),
        ))

    nba = _next_best_actions(top, cart)
    return recs, nba


def _suggest_bundle(e: EligibleProduct) -> list[str]:
    p = e.product
    bundle = []
    if p.type.value == "phone":
        if p.compatible_plans:
            bundle.append(p.compatible_plans[0])
        bundle.append("accessory_case")
    return bundle


def _next_best_actions(top: list[EligibleProduct], cart: Cart | None) -> list[str]:
    nba: list[str] = []
    if top and top[0].product.type.value == "phone":
        nba.append("Add a protective case for €15 to keep it safe?")
    if cart is not None:
        remaining = cart.free_shipping_threshold - cart.subtotal
        if 0 < remaining <= 20:
            nba.append(f"You're €{int(remaining)} away from free shipping.")
    return nba


_WHY_SYSTEM_PROMPT = """You write ONE short, warm sentence explaining why a \
product fits a Telekom shopping customer. Ground it STRICTLY in the "Product"
fields given - never mention a feature, spec, or price the product doesn't
have. If the profile gives no clear match, say it's a solid all-round fit
within any stated budget. Output ONLY the sentence, no quotes, no preamble."""


def _why_openai(e: EligibleProduct, profile: PreferenceProfile) -> str:
    from openai import OpenAI  # heavy import, kept local

    from app.config import OPENAI_API_KEY, OPENAI_MODEL

    if not OPENAI_API_KEY:
        raise RuntimeError("OPENAI_API_KEY not set")

    p = e.product
    price_fragment = f"€{p.price_monthly}/mo" if p.price_monthly else f"€{p.price_onetime} one-time"
    product_facts = (
        f"Product: {p.name} by {p.brand}. Type: {p.type.value}. "
        f"Features: {', '.join(p.features) or 'none listed'}. "
        f"Price: {price_fragment}."
    )
    profile_facts = (
        f"Customer profile - budget: {profile.budget_monthly_max or 'not specified'} EUR/mo, "
        f"features they mentioned: {', '.join(profile.features_mentioned) or 'none'}, "
        f"brands they've viewed: {', '.join(profile.brands_viewed) or 'none'}."
    )

    client = OpenAI(api_key=OPENAI_API_KEY)
    resp = client.chat.completions.create(
        model=OPENAI_MODEL,
        messages=[
            {"role": "system", "content": _WHY_SYSTEM_PROMPT},
            {"role": "user", "content": f"{product_facts}\n{profile_facts}"},
        ],
        temperature=0.4,
        max_tokens=80,
        timeout=15,
    )
    text = (resp.choices[0].message.content or "").strip()
    if not text:
        raise RuntimeError("empty response from OpenAI")
    return text
